# --- Gateway Connection ---
disable_anonymized_analytics: true
gateways:
  duckdb_local:
    state_connection: 
      type: duckdb
      database: data/sqlmesh_state.db
    connection:
      type: duckdb
      database: data/swell_tags.db
      extensions: 
        - spatial
  duckdb_s3:
    state_connection: 
      type: duckdb
      database: data/sqlmesh_state.db
    connection:
      type: duckdb
      database: s3://swell-tags-data/swell_tags.db
      extensions: 
        - spatial
        - httpfs
      secrets:
        - type: s3
          region: {{ env_var('AWS_REGION') }}
          key_id: {{ env_var('AWS_ACCESS_KEY_ID') }}
          secret: {{ env_var('AWS_SECRET_ACCESS_KEY') }}
default_gateway: duckdb_local

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 2026-07-19 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    # - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections


