# --- Gateway Connection ---
disable_anonymized_analytics: true
cache_dir: "{{ env_var('SQLMESH_CACHE_DIR', './') }}"
gateways:
  duckdb_local:
    state_connection:
      type: duckdb
      database: data/sqlmesh_state.db
    connection:
      type: duckdb
      database: data/swell_tags.db
      extensions:
        - spatial
  duckdb_s3:
    state_connection:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PORT', 5432) }}"
      user: "{{ env_var('PGUSER')}}"
      password: "{{ env_var('PGPASSWORD')}}"
      database: "{{ env_var('PGDATABASE')}}"
    connection:
      type: duckdb
      catalogs:
        remote: "s3://swell-tags-us-east-1/duck/swell_tags.duckdb"
before_all:
  - "@IF(@gateway = 'duckdb_s3', @load_s3_lambda_creds())"

default_gateway: duckdb_local

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 2026-07-19 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    # - ambiguousorinvalidcolumn
    # - invalidselectstarexpansion
    - noambiguousprojections


