variables:
  # hey this empty list will ignore the spatial filter!
  parent_quadkey: "{{ env_var('PARENT_QUADKEY', '') }}"
  parent_bbox: "{{ env_var('PARENT_BBOX', 'POLYGON ((-117.611081 32.528832, -117.611081 33.505025, -116.08094 33.505025, -116.08094 32.528832, -117.611081 32.528832))') }}"

# --- Gateway Connection ---
gateways:
  duckdb:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: duckdb
      database: ndbc.db
      # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # catalogs: 
      extensions: 
      - spatial
      # connector_config: 
      # secrets: 
      # filesystems: 
      # token: 

default_gateway: duckdb

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 2026-07-19 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    # - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
